import {Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow} from "@mui/material";

export default function Limits({rows}) {
    return (
        <TableContainer component={Paper}>
            <Table sx={{minWidth: 650}} aria-label="simple table">
                <TableHead>
                    <TableRow>
                        <TableCell
                            sx={{
                                fontWeight:"bold",
                                fontSize:"large",
                                p:1
                            }}
                        >
                            Name
                        </TableCell>
                        <TableCell
                            sx={{
                                fontWeight:"bold",
                                fontSize:"large",
                                p:1
                            }}
                            align="right"
                        >
                            Last
                        </TableCell>
                        <TableCell
                            sx={{
                                fontWeight:"bold",
                                fontSize:"large",
                                p:1
                            }}
                            align="right"
                        >
                            Min
                        </TableCell>
                        <TableCell
                            sx={{
                                fontWeight:"bold",
                                fontSize:"large",
                                p:1
                            }}
                            align="right"
                        >
                            Avg
                        </TableCell>
                        <TableCell
                            sx={{
                                fontWeight:"bold",
                                fontSize:"large",
                                p:1
                            }}
                            align="right"
                        >
                            Max
                        </TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>
                    {rows.map((row) => (
                        <TableRow key={row.name} sx={{'&:last-child td, &:last-child th': {border: 0}}}>
                            <TableCell
                                sx={{
                                    fontSize:"large",
                                    p:1
                                }}
                                component="th"
                                scope="row"
                            >
                                {row.name}
                            </TableCell>
                            <TableCell
                                sx={{
                                    fontSize:"large",
                                    p:1
                                }}
                                align="right"
                            >
                                {row.last}
                            </TableCell>
                            <TableCell
                                sx={{
                                    fontSize:"large",
                                    p:1
                                }}
                                align="right"
                            >
                                {row.min}
                            </TableCell>
                            <TableCell
                                sx={{
                                    fontSize:"large",
                                    p:1
                                }}
                                align="right"
                            >
                                {row.avg}
                            </TableCell>
                            <TableCell
                                sx={{
                                    fontSize:"large",
                                    p:1
                                }}
                                align="right"
                            >
                                {row.max}
                            </TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
        </TableContainer>
    );
}